# Generated by Django 4.2.7 on 2023-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('usuario', 'usuario')], max_length=10, null=True),
        ),
    ]
