# Generated by Django 4.2.7 on 2023-12-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
    ]
