# Generated by Django 4.2.7 on 2023-12-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0002_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primerapp', to='primerapp.ciudad'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
    ]
