# Generated by Django 4.2.7 on 2023-12-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0004_item_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fecha',
        ),
    ]
