# Generated by Django 4.2.7 on 2023-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0006_rename_costo_mensual_item_costo_alter_ciudad_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ciudades'),
        ),
    ]
