# Generated by Django 4.2.7 on 2023-12-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0007_ciudad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='imagen',
            field=models.ImageField(upload_to='ciudades'),
        ),
    ]
