# Generated by Django 4.2.7 on 2023-12-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0009_alter_ciudad_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='imagen',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='img_postal',
            field=models.ImageField(blank=True, null=True, upload_to='ciudades'),
        ),
    ]
