# Generated by Django 4.2.7 on 2023-12-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0010_remove_ciudad_imagen_ciudad_img_postal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='img_postal',
            new_name='imagen',
        ),
    ]
