# Generated by Django 4.2.7 on 2023-12-21 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0011_rename_img_postal_ciudad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
