# Generated by Django 4.2.7 on 2023-12-21 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0012_item_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
