# Generated by Django 4.2.7 on 2023-12-23 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0013_item_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 23, 0, 42, 4, 640693, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2023, 12, 23, 0, 42, 4, 640693, tzinfo=datetime.timezone.utc)),
        ),
    ]
