# Generated by Django 4.2.7 on 2023-12-23 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0014_alter_item_fecha_alter_item_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='actualizado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
