# Generated by Django 4.2.7 on 2023-12-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0015_item_actualizado_alter_item_fecha_alter_item_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hora',
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
