# Generated by Django 4.2.7 on 2023-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0017_item_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
